config/urls.py
from django.contrib import admin
from django.urls import path, include
from kairos.usuarios.views import inicio
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", inicio, name='inicio'),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    #path('auth/', include('magiclink.urls', namespace='magiclink')),
    path('app/usuarios/', include('kairos.usuarios.urls', namespace='usuarios')),
    path('app/organizaciones/', include('kairos.organizaciones.urls', namespace='organizaciones')),
    path('app/perfiles-deseados/', include('kairos.perfiles_deseados.urls', namespace='perfiles_deseados')),
    path('app/intereses/', include('kairos.intereses.urls', namespace='intereses')),
    path('app/retos/', include('kairos.retos.urls', namespace='retos')),
    path('app/contenido/', include('kairos.contenido.urls', namespace='contenido')),
    path('app/insignias/', include('kairos.insignias.urls', namespace='insignias')),
    path('app/cuestionarios/', include('kairos.formularios.urls', namespace='formularios')),
    path('app/calificaciones/', include('kairos.calificaciones.urls', namespace='calificaciones')),
    path('app/tandas/', include('kairos.tandas_formularios.urls', namespace='tandas')),
    path('app/tablero-organizaciones/', include('kairos.tableros.tablero_organizaciones.urls', namespace='tablero_organizaciones')),
    path('app/tablero-jovenes/', include('kairos.tableros.tablero_jovenes.urls', namespace='tablero_jovenes')),
    path('app/tablero-auditorias/', include('kairos.tableros.tablero_auditorias.urls', namespace='tablero_auditorias')),
    path('app/equipos/', include('kairos.equipos.urls', namespace='equipos')),
    path('app/auditorias/', include('kairos.auditorias.urls', namespace='auditorias')),
    path('app/guia/', include('kairos.guia.urls', namespace='guia')),
    path('app/ranking/', include('kairos.ranking.urls', namespace='ranking')),
    path('app/pqrs/', include('kairos.pqrs.urls', namespace='pqrs')),
    path('app/cuartos/', include('kairos.cuartos.urls', namespace='cuartos')),
    path('app/jurados/', include('kairos.jurados.urls', namespace='jurados')),
    path('app/habilidades-del-futuro/', include('kairos.habilidades_del_futuro.urls', namespace='habilidades_del_futuro')),

    path('select2/', include('django_select2.urls')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Handler errors
handler404 = 'kairos.error.views.error_404'
handler500 = 'kairos.error.views.error_500'

kairos/error/urls.py
from . import views
from django.urls import path

app_name = "error"

kairos/guia/urls.py
# Modulos Django
from django.urls import path

# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from . import views

app_name = "guia"

urlpatterns = [
    path('listado', views.ListadoRecursos.as_view(), name='listado'),
    path('registrar', views.RecursoRegistrar.as_view(), name='registrar'),
    path('modificar/<int:id_recurso>', views.ModificarRecurso.as_view(), name='modificar'),

    path('tipos/gestionar/',  views.ListadoTipoRecursos.as_view(), name='listado_tipo'),
    path('tipos/registrar',  views.TipoRecursoRegistrar.as_view(), name='registrar_tipo'),
    path('tipos/modificar/<int:id_tipo_recurso>',  views.ModificarTipoRecurso.as_view(), name='modificar_tipo'),

    path('guia-eslabon', views.ConsultarJovenesGuia.as_view(), name='consultar_guia_jovenes'),
    path("api/cargar-calificaciones", views.ApiCargarCalificaciones.as_view(), name="api_cargar_calificaciones"),
    path("api/calificar", views.ApiCalificar.as_view(), name="api_calificar"),
    path("api/realidad", views.APIRecursosRealidad.as_view(), name="api_realidad"),
]

kairos/insignias/urls.py
# Modulos Django
from django.urls import path

# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from .views import *

app_name = "insignias"

urlpatterns = [
    path('tribus/gestionar/', TribusListado.as_view(), name='listado_tribus'),
    path('tribus/consultar/', TribusConsultar.as_view(), name='consultar_tribus'),
    path('tribus/registrar', TribuRegistrar.as_view(), name='registrar_tribu'),
    path('tribus/modificar/<int:id_tribu>', TribuModificar.as_view(), name='modificar_tribu'),

    path('familias/gestionar/', FamiliasListado.as_view(), name='listado_familias'),    
    path('familias/registrar', FamiliaRegistrar.as_view(), name='registrar_familia'),
    path('familias/modificar/<int:id_familia>', FamiliaModificar.as_view(), name='modificar_familia'),

    path('campos/gestionar/', CamposListado.as_view(), name='listado_campos'),    
    path('campos/registrar', CampoRegistrar.as_view(), name='registrar_campo'),
    path('campos/modificar/<int:id_campo>', CampoModificar.as_view(), name='modificar_campo'),

    path('niveles-conocimiento/gestionar/', NivelesDeConocimientoListado.as_view(), name='listado_niveles'),
    path('niveles-conocimiento/consultar/', NivelesDeConocimientoConsultar.as_view(), name='consultar_niveles'),
    path('niveles-conocimiento/registrar', NivelesDeConocimientoRegistrar.as_view(), name='registrar_nivel'),
    path('niveles-conocimiento/modificar/<int:id_nivel>', NivelesDeConocimientoModificar.as_view(), name='modificar_nivel'),

    path('roles/gestionar/', RolesListado.as_view(), name='listado_roles'),
    path('roles/consultar/', RolesConsultar.as_view(), name='consultar_roles'),
    path('roles/registrar', RolesRegistrar.as_view(), name='registrar_rol'),
    path('roles/modificar/<int:id_rol>', RolesModificar.as_view(), name='modificar_rol'),

    path('joven/consultar/', InsigniasConsultar.as_view(), name='consultar_insignias'),

    path('tipo-equipo/gestionar/', TipoDeEquipoListado.as_view(), name='listado_tipo_equipo'),
    path('tipo-equipo/consultar/', TipoDeEquipoConsultar.as_view(), name='consultar_tipo_equipo'),
    path('tipo-equipo/registrar', TipoDeEquipoRegistrar.as_view(), name='registrar_tipo_equipo'),
    path('tipo-equipo/modificar/<int:id_tipo_equipo>', TipoDeEquipoModificar.as_view(), name='modificar_tipo_equipo'),

]

kairos/pqrs/urls.py
# Modulos Django
from django.urls import path
# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from .views import *

app_name = "pqrs"

urlpatterns = [
    path('enviar/', CrearSolicitudPQRS.as_view(), name='enviar_pqrs'),
]

kairos/auditorias/models.py
from django.db import models

kairos/formularios/models.py
# Modulos Django
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinValueValidator, MaxValueValidator

# Modulos de plugin externos
import os

# Modulos de otras apps
from simple_history.models import HistoricalRecords


# Modulos de otras apps

# Modulos internos de la app

def subir_img_formulario(instance, filename):
    ext = filename.split('.')[-1]  # eg: 'jpg'
    renamed_filename = '%(formulario)s_%(id)s.%(ext)s' % {'formulario': instance.nombre, 'id': instance.id, 'ext': ext}
    return os.path.join('formularios/', renamed_filename)


def subir_img_pregunta(instance, filename):
    ext = filename.split('.')[-1]  # eg: 'jpg'
    # eg: 'nombreformulario_idpregunta.jpg'
    renamed_filename = '%(formulario)s_%(id)s.%(ext)s' % {'formulario': instance.formulario.nombre, 'id': instance.id,
                                                          'ext': ext}
    # eg: 'formularios/preguntas/nombreformulario_id.jpg'
    return os.path.join('formularios/preguntas/', renamed_filename)


def subir_img_respuesta(instance, filename):
    ext = filename.split('.')[-1]  # eg: 'jpg'
    # eg: 'nombreformulario_idrespuesta.jpg'
    renamed_filename = '%(formulario)s_%(id)s.%(ext)s' % {'formulario': instance.formulario.nombre, 'id': instance.id,
                                                          'ext': ext}
    # eg: 'iconos_sistema/nombre.png'
    return os.path.join('formularios/respuestas/', renamed_filename)


def subir_competencia(instance, filename):
    return "competencias/{}".format(
        filename.encode('ascii', 'ignore'),
    )


class Competencias(models.Model):
    CODIGO_CALIFICACIONES = (
        ('Números', 'Números'),
        ('Lectura', 'Lectura'),
        ('Negociación', 'Negociación'),
        ('Autoconciencia', 'Autoconciencia'),
        ('Empatía', 'Autoconciencia'),
        ('Autocontrol', 'Autocontrol'),
        ('Autoconfianza', 'Autoconfianza'),
        ('Dirección', 'Dirección'),
        ('Carisma', 'Carisma'),
        ('Innovación', 'Innovación'),
        ('Desarrollo', 'Desarrollo'),
        ('Motivación', 'Motivación'),
        ('Inspiración', 'Inspiración'),
        ('Socializar', 'Socializar'),
        ('Liderazgo_laizzes_faire', 'Liderazgo Laizzes Faire'),
        ('Liderazgo_transaccional', 'Liderazgo Transaccional'),
        ('Liderazgo_transformacional', 'Liderazgo Transformacional'),
    )

    nombre = models.CharField(max_length=100, verbose_name="nombre de la competencia")
    explicacion = models.TextField(verbose_name="definición y explicación de niveles")
    necesidad = models.TextField(verbose_name="¿Para qué es necesario en la vida?")
    desarrollo = models.TextField(verbose_name="¿Cómo se puede desarrollar?")
    activo = models.BooleanField(verbose_name="¿La competencia se encuentra activa?", default=True)
    imagen = models.FileField(upload_to=subir_competencia, blank=True, null=True)
    codigo_calificacion = models.CharField(max_length=30, choices=CODIGO_CALIFICACIONES, blank=True, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.nombre

    @staticmethod
    def buscar(id_competencia) -> 'Competencias':
        '''
            Función que busca una competencia por id_competencia y retorna
            la competencia.
        '''
        competencia = Competencias.objects.get(id=id_competencia)
        return competencia

    def crear_competencia_visitada_joven(self, id_usuario: int):
        '''
            Función que crea la competencia visitada para el joven
        '''
        CompetenciaVisitada.objects.get_or_create(
            usuario_id=id_usuario,
            competencia_id=self.pk
        )

    def calificar_competencia_joven(self, id_usuario: str):
        '''
            Función que califica la competencia como visitada
        '''
        try:
            competencia_visitada = CompetenciaVisitada.objects.get(
                competencia_id=self.id,
                usuario_id=id_usuario
            )
            if competencia_visitada.visitado == 0:
                competencia_visitada.visitado = 1
                competencia_visitada.save()
        except CompetenciaVisitada.DoesNotExist:
            return None


class Ambito(models.Model):
    nombre = models.CharField(max_length=50, verbose_name="nombre del ámbito")
    descripcion = models.CharField(max_length=300, verbose_name="descripción")
    activo = models.BooleanField(verbose_name="¿El ámbito se encuentra activo?", default=True)
    competencias = models.ManyToManyField(Competencias, related_name="ambito_compentecias")
    history = HistoricalRecords()

    def __str__(self):
        return self.nombre


class Formularios(models.Model):
    ambito = models.ForeignKey('Ambito', on_delete=models.CASCADE, verbose_name="Ámbito*")
    nombre = models.CharField(max_length=50, verbose_name="nombre del formulario*")
    identificador = models.PositiveIntegerField(verbose_name='identificador*')
    TIPOS_DE_PREGUNTA = (
        ("SM", "Selección Múltiple"),
        ("E", "Escala de Valoración Numérica"),
        ("SN", "Si/No"),
        ("D48", "D48 - Dominó"),
        ("T", "Texto Libre")
    )
    tipo_preguntas = models.CharField(max_length=100, choices=TIPOS_DE_PREGUNTA,
                                      verbose_name='tipo de preguntas', default="SM")
    descripcion = models.TextField(verbose_name="insumo", blank=True, null=True)
    instrucciones = models.TextField(verbose_name="indicaciones*")
    imagen = models.FileField(upload_to=subir_img_formulario, blank=True, null=True, verbose_name="imagen instructiva")
    escala_max = models.IntegerField(validators=[MinValueValidator(2), MaxValueValidator(6)],
                                     verbose_name="escala máxima (si aplica)", null=True, blank=True)
    credito = models.CharField(max_length=200, verbose_name='crédito', null=True, blank=True)
    tiempo_lectura = models.PositiveIntegerField(validators=[MinValueValidator(1)],
                                                 verbose_name="tiempo límite para lectura del texto (minutos)",
                                                 null=True, blank=True)
    tiempo_limite = models.PositiveIntegerField(validators=[MinValueValidator(1)],
                                                verbose_name="tiempo límite para su solución (minutos)", null=True,
                                                blank=True)
    releer = models.BooleanField(verbose_name="¿El joven puede volver al texto descriptivo?", default=False)
    activo = models.BooleanField(verbose_name="¿El formulario se encuentra activo?", default=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.nombre

    @staticmethod
    def cantidad_formularios_activos(formularios: 'QuerySet<Formularios>', joven: 'Joven') -> 'int':
        from django.db.models import Q
        '''
            Filtra por respuestasjoven__joven y/o respuestasjoven__completas  y retorna la cantidad total.
            Parametros:
                formularios (QuerySet<Formularios>): Formularios  del Joven.
                joven (Joven): Joven dueño de los formularios.
            Retorno:
                Cantidad (int): de cantidad de Formularios filtrados.
        '''
        cantidad_formularios = formularios.filter(~Q(respuestasjoven__joven=joven.id) |
                                                  Q(respuestasjoven__joven=joven.id,
                                                    respuestasjoven__completas=False)).order_by(
            'pk').distinct().count()
        return cantidad_formularios

    class Meta:
        ordering = ['identificador']

    # def formulario_completo(self, joven):
    #     try:
    #         RespuestasJoven.objects.get(joven=joven.pk, tanda=joven.tanda_formularios.pk, completas=True)
    #         return True
    #     except:
    #         return False


class Preguntas(models.Model):
    formulario = models.ForeignKey(Formularios, related_name="pregunta_del_formulario", on_delete=models.CASCADE,
                                   verbose_name="formulario al que pertenece*")
    competencia = models.ForeignKey(Competencias, on_delete=models.CASCADE,
                                    verbose_name="competencia que mide la pregunta", null=True, blank=False)
    identificador = models.CharField(max_length=20, verbose_name="identificador de la pregunta", null=True, blank=True,
                                     unique=True)  # idformulario_numpregunta
    TIPOS_DE_PREGUNTA = (
        ("SM", "Selección Múltiple"),
        ("E", "Escala de Valoración Numérica"),
        ("T", "Texto Libre"),
        ("SN", "Si/No"),
    )
    tipo = models.CharField(max_length=100, choices=TIPOS_DE_PREGUNTA,
                            verbose_name='tipo de pregunta', default="SM")
    descripcion = models.CharField(max_length=300, verbose_name="descripción")
    imagen = models.FileField(upload_to=subir_img_pregunta, blank=True, null=True)
    activo = models.BooleanField(verbose_name="¿La pregunta se encuentra activa?", default=True)
    history = HistoricalRecords()

    def get_correctas(self):
        respuestas = Respuestas.objects.filter(pregunta=self.id, correcta=True)
        return respuestas

    def __str__(self):
        return self.descripcion


class Respuestas(models.Model):
    pregunta = models.ForeignKey(Preguntas, related_name="respuesta_pregunta", on_delete=models.CASCADE,
                                 verbose_name="pregunta a la que pertenece*")
    descripcion = models.CharField(max_length=300, verbose_name="descripción")
    correcta = models.BooleanField(verbose_name="¿la respuesta es correcta?", default=False)
    imagen = models.FileField(upload_to=subir_img_respuesta, blank=True, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.descripcion


class SeccionVisitada(models.Model):

kairos/intereses/models.py
# Modulos Django
from django.db import models

# Modulos de plugin externos
from simple_history.models import HistoricalRecords

# Modulos de otras apps
# Modulos internos de la app

class Intereses(models.Model):
    nombre = models.CharField(max_length=50, verbose_name='nombre del interés*')
    descripcion = models.TextField(verbose_name='descripción*')
    activo = models.BooleanField(verbose_name="¿El interés se encuentra activo?", default=True)
    history = HistoricalRecords()

kairos/ranking/models.py
from django.db import models

# Create your models here.

kairos/tableros/tablero_auditorias/models.py
from django.db import models

# Create your models here.

kairos/templates/insignias/tribus/consultar.html
{% extends 'base_tablas.html' %}

{% block titulo %}
    Gestión Tribus
{% endblock titulo %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="{% url "inicio" %}">Inicio</a></li>
    <li class="breadcrumb-item">Módulo Insignias</li>
    <li class="breadcrumb-item active">Gestión Familias</li>
{% endblock miga_pan %}

{% block titulo_pagina %}
    <i class="icon-badge icon-orange"></i> Gestión Familias
{% endblock titulo_pagina %}

{% block contenido_panel %}
    <div class="row m-b-9">
        <div class="col-md-12">
            <p class="mb-1">
                <i>A continuación se presentan las Familias registradas en el sistema.</i>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-12 m-t-5">
            <div class="table-fix">
                <table class="table table-bordered table-striped table-td-valign-middle datatable">
                    <thead>
                    <tr>
                        <th>Nombre de la Familia</th>
                        <th>Descripción</th>
                        <th>Campos</th>
                        <th>Imagen</th>
                        <th>Estado</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for tribu in tribus %}
                        <tr>
                            <td>{{tribu.nombre}}</td>
                            <td>{{tribu.descripcion}}</td>
                            <td>{{tribu.rutas_de_conocimiento_de_la_tribu.all|join:', '|default:'Sin rutas de conocimiento'}}</td>
                            <td align="center">
                                {% if tribu.imagen  %}
                                    <a href="{{tribu.imagen.url}}" data-lightbox="gallery-group">
                                        <div>
                                            <img style="max-width: 50px" src="{{tribu.imagen.url}}" class="img img-fluid centerImage">
                                        </div>
                                    </a>
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if tribu.activo == True %}
                                    <span class="label label-lime">ACTIVA</span>
                                {% else %}
                                    <span class="label label-secondary">INACTIVA</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock contenido_panel %}

kairos/templates/insignias/tribus/listado.html
{% extends 'base_tablas.html' %}

{% block titulo %}
    Gestión Tribus
{% endblock titulo %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="{% url "inicio" %}">Inicio</a></li>
    <li class="breadcrumb-item">Módulo Insignias</li>
    <li class="breadcrumb-item active">Gestión Tribus</li>
{% endblock miga_pan %}

{% block titulo_pagina %}
    <i class="icon-badge icon-orange"></i> Gestión Tribus
{% endblock titulo_pagina %}

{% block contenido_panel %}
    <div class="row m-b-9">
        <div class="col-md-12">
            <p class="mb-1">
                <i>Tribus registradas: {{ tribus|length }}</i>
            </p>
        </div>
        <div class="col-md-12" align="right">
            <a class="btn btn-primary" href="{% url "insignias:registrar_tribu" %}"><i class="fas fa-plus"></i> Registrar Tribu</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12 m-t-5">
            <div class="table-fix">
                <table class="table table-bordered table-striped table-td-valign-middle datatable">
                    <thead>
                    <tr>
                        <th>Nombre de la Tribu</th>
                        <th>Interés/Aptitud</th>
                        <th>Descripción</th>
                        <th>Familias</th>
                        <th>Imagen</th>
                        <th>Estado</th>
                        <th style="min-width: 50px;"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for tribu in tribus %}
                        <tr>
                            <td>{{tribu.nombre}}</td>
                            <td>{{tribu.get_interes_aptitud_display}}</td>
                            <td>{{tribu.descripcion}}</td>
                            <td>{{tribu.familias_de_la_tribu.all|join:', '|default:'Sin Familias'}}</td>
                            <td align="center">
                                {% if tribu.imagen  %}
                                    <a href="{{tribu.imagen.url}}" data-lightbox="gallery-group">
                                        <div>
                                            <img style="max-width: 50px" src="{{tribu.imagen.url}}" class="img img-fluid centerImage">
                                        </div>
                                    </a>
                                {% endif %}
                            </td>
                            <td align="center">
                                {% if tribu.activo == True %}
                                    <span class="label label-lime">ACTIVA</span>
                                {% else %}
                                    <span class="label label-secondary">INACTIVA</span>
                                {% endif %}
                            </td>
                            <td align="center">
                                <div class="row">
                                    {#                                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">#}
                                    {#                                        <a title="Ver Respuestas" href="#"><i class="fas fa-eye"></i></a>#}
                                    {#                                    </div>#}
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <a title="Modificar" href="{% url "insignias:modificar_tribu" tribu.id %}"><i class="fas fa-pen-alt"></i></a>
                                    </div>
                                    {#                                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">#}
                                    {#                                        <a title="Activar/Inactivar" href="#"><i class="fas fa-trash-alt"></i></a>#}
                                    {#                                    </div>#}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock contenido_panel %}

kairos/templates/insignias/tribus/modificar.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load static %}

{% block titulo %}
    Modificar Tribu
{% endblock titulo %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="{% url "inicio" %}">Inicio</a></li>
    <li class="breadcrumb-item">Módulo Insignias</li>
    <li class="breadcrumb-item"><a href="{% url "insignias:listado_tribus" %}">Gestión Tribus</a></li>
    <li class="breadcrumb-item active">Modificar Tribu</li>
{% endblock miga_pan %}

{% block titulo_pagina %}
    <i class="icon-badge icon-orange"></i> Modificar Tribu
{% endblock titulo_pagina %}

{% block contenido_panel %}
    <form enctype="multipart/form-data" method="post">{% csrf_token %}
        <div class="row">
            <div class="col-12 mb-2">
                <p class="mb-1">
                    <i>El siguiente formulario permite modificar las diferentes características de una tribu.</i>
                </p>
            </div>
            <div class="col-12">
                <div class="row">
                    {% for field in form %}                              
                        {% if field.name == 'imagen'  %}
                            <div class="col-lg-6 mt-5 p-0">
                                <div class="custom-file col-md-12">                                
                                    <input type="file" accept="image/*" name="imagen" class="custom-file-input" id="id_imagen">
                                    <label style="height: calc(1.2em + 14px + 2px);" class="custom-file-label" for="id_imagen">{{form.imagen.value|default:' Seleccione un logo...'}}</label>
                                </div>
                                <div class="col-md-12 form-check checkbox checkbox-css pt-0 checkbox-inline">
                                    <div class="form-check pl-0">
                                        <input type="checkbox" class="form-check-input" name="imagen-clear" id="id_imagen-clear_id">
                                        <label class="form-check-label" for="id_imagen-clear_id">Limpiar selección</label>
                                    </div>
                                </div>
                            </div>                                
                        {% else %}
                            <div class="col-lg-6">
                                {% bootstrap_field field%}
                            </div>   
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="col-6" align="left">
                        <a class="btn btn-secondary" href="{% url "insignias:listado_tribus" %}"><i class="fa fa-angle-left"></i> Volver</a>
                    </div>
                    <div class="col-6" align="right">
                        <button class="btn btn-primary" type="submit">Modificar Tribu <i class="fa fa-angle-right"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock contenido_panel %}

{% block js %}
    <!--  <script src="{% static 'plugins/select2/dist/js/select2.full.min.js' %}"></script> -->
    <script>
        document.querySelector('.custom-file-input').addEventListener('change',function(e){
            var fileName = document.getElementById("id_imagen").files[0].name;
            var nextSibling = e.target.nextElementSibling;
            nextSibling.innerText = fileName;
        });
    </script>
{% endblock js %}

kairos/templates/insignias/tribus/registrar.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load static %}

{% block titulo %}
    Registrar Tribu
{% endblock titulo %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="{% url "inicio" %}">Inicio</a></li>
    <li class="breadcrumb-item">Módulo Insignias</li>
    <li class="breadcrumb-item"><a href="{% url "insignias:listado_tribus" %}">Gestión Tribus</a></li>
    <li class="breadcrumb-item active">Registrar Tribu</li>
{% endblock miga_pan %}

{% block titulo_pagina %}
    <i class="icon-badge icon-orange"></i> Registrar Tribu
{% endblock titulo_pagina %}

{% block contenido_panel %}
    <form enctype="multipart/form-data" method="post">{% csrf_token %}
        <div class="row">
            <div class="col-12 mb-2">
                <p class="mb-1">
                    <i>El siguiente formulario permite el registro de una tribu.</i>
                </p>
            </div>
            <div class="col-12">
                <div class="row">
                    {% for field in form %}
                        {% if field.name == 'imagen'  %}
                            <div class="col-lg-6 mt-5 p-0">
                                <div class="custom-file col-md-12">                                
                                    <input type="file" accept="image/*" name="imagen" class="custom-file-input" id="id_imagen">
                                    <label style="height: calc(1.2em + 14px + 2px);" class="custom-file-label" for="id_imagen">{{form.imagen.value|default:' Seleccione un logo...'}}</label>
                                </div>
                                <div class="col-md-12 form-check checkbox checkbox-css pt-0 checkbox-inline">
                                    <div class="form-check pl-0">
                                        <input type="checkbox" class="form-check-input" name="imagen-clear" id="id_imagen-clear_id">
                                        <label class="form-check-label" for="id_imagen-clear_id">Limpiar selección</label>
                                    </div>
                                </div>
                            </div>                                
                        {% else %}
                            <div class="col-lg-6">
                                {% bootstrap_field field%}
                            </div>   
                        {% endif %}                      
                    {% endfor %}
                </div>
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="col-6" align="left">
                        <a class="btn btn-secondary" href="{% url "insignias:listado_tribus" %}"><i class="fa fa-angle-left"></i> Volver</a>
                    </div>
                    <div class="col-6" align="right">
                        <button class="btn btn-primary" type="submit">Registrar Tribu <i class="fa fa-angle-right"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock contenido_panel %}

{% block js %}
    <!--   <script src="{% static 'plugins/select2/dist/js/select2.full.min.js' %}"></script> -->
    <script>
        document.querySelector('.custom-file-input').addEventListener('change',function(e){
            var fileName = document.getElementById("id_imagen").files[0].name;
            var nextSibling = e.target.nextElementSibling;
            nextSibling.innerText = fileName;
        });
    </script>
{% endblock js %}