config/urls.py
from django.contrib import admin
from django.urls import path, include
from kairos.usuarios.views import inicio
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", inicio, name='inicio'),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    #path('auth/', include('magiclink.urls', namespace='magiclink')),
    path('app/usuarios/', include('kairos.usuarios.urls', namespace='usuarios')),
    path('app/organizaciones/', include('kairos.organizaciones.urls', namespace='organizaciones')),
    path('app/perfiles-deseados/', include('kairos.perfiles_deseados.urls', namespace='perfiles_deseados')),
    path('app/intereses/', include('kairos.intereses.urls', namespace='intereses')),
    path('app/retos/', include('kairos.retos.urls', namespace='retos')),
    path('app/contenido/', include('kairos.contenido.urls', namespace='contenido')),
    path('app/insignias/', include('kairos.insignias.urls', namespace='insignias')),
    path('app/cuestionarios/', include('kairos.formularios.urls', namespace='formularios')),
    path('app/calificaciones/', include('kairos.calificaciones.urls', namespace='calificaciones')),
    path('app/tandas/', include('kairos.tandas_formularios.urls', namespace='tandas')),
    path('app/tablero-organizaciones/', include('kairos.tableros.tablero_organizaciones.urls', namespace='tablero_organizaciones')),
    path('app/tablero-jovenes/', include('kairos.tableros.tablero_jovenes.urls', namespace='tablero_jovenes')),
    path('app/tablero-auditorias/', include('kairos.tableros.tablero_auditorias.urls', namespace='tablero_auditorias')),
    path('app/equipos/', include('kairos.equipos.urls', namespace='equipos')),
    path('app/auditorias/', include('kairos.auditorias.urls', namespace='auditorias')),
    path('app/guia/', include('kairos.guia.urls', namespace='guia')),
    path('app/ranking/', include('kairos.ranking.urls', namespace='ranking')),
    path('app/pqrs/', include('kairos.pqrs.urls', namespace='pqrs')),
    path('app/cuartos/', include('kairos.cuartos.urls', namespace='cuartos')),
    path('app/jurados/', include('kairos.jurados.urls', namespace='jurados')),
    path('app/habilidades-del-futuro/', include('kairos.habilidades_del_futuro.urls', namespace='habilidades_del_futuro')),

    path('select2/', include('django_select2.urls')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Handler errors
handler404 = 'kairos.error.views.error_404'
handler500 = 'kairos.error.views.error_500'

kairos/equipos/urls.py
# Modulos Django
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from .views import *

app_name = "equipos"

urlpatterns = [
    path('gestionar', view=GestionDeEquiposLider.as_view(), name='gestionar_equipos'),
    path('registrar', view=EquipoRegistrar.as_view(), name='registrar'),
    path('<int:id_equipo>/registrar-proyecto', view=RegistroDeProyectos, name='registrar_proyecto'),
    path('<int:id_equipo>/enviar-invitaciones', view=RegistroDeInvitaciones, name='enviar_invitaciones'),
    path('cancelar-invitacion/<int:id_joven>/<int:id_equipo>', view=CancelarInvitacion, name='cancelar_invitacion'),

    path('todos-los-equipos', view=EquipoConsultar.as_view(), name='consultar_todos_los_equipos'),
    path('modificar-equipo/<int:id_equipo>', view=ModificarEquipo.as_view(), name='modificar_equipo'),
    path('modificar-proyecto/<int:id_proyecto>', view=ModificarProyecto.as_view(), name='modificar_proyecto'),
    path('gestion-solicitudes', view=GestionDeSolicitudesEquipos.as_view(), name='gestionar_solicitudes'),

    path('detalle-perfil/<int:id_equipo>', view=EquipoDetalle.as_view(), name='detalle_equipo'),
    path('quienes-somos/<int:id_equipo>', view=QuienesSomosEquipoDetalle.as_view(), name='quienes_somos'),
    path('miembros/<int:id_equipo>', view=MiembrosEquipoDetalle.as_view(), name='miembros'),
    path('estado/<int:id_equipo>', view=EstadoEquipoDetalle.as_view(), name='estado'),

    path("api/cargar-calificaciones", view=ApiCargarCalificaciones.as_view(), name="api_cargar_calificaciones"),
    path("api/cargar-calificacion", view=ApiCargarCalificacion.as_view(), name="api_cargar_calificacion"),
    path("api/calificar", view=ApiCalificarContenido.as_view(), name="api_calificar"),
    path("api/validar-equipos", view=ApiValidacionEquipos.as_view(), name="api_validar_equipos"),    

    path('postularme/<int:id_joven>/<int:id_equipo>', view=Postularme, name='postularme'),
    path('aceptar-postulacion/<int:id_joven>/<int:id_equipo>', view=AceptarPostulacion, name='aceptar_postulacion'),
    path('aceptar-invitacion/<int:id_joven>/<int:id_equipo>', view=AceptarInvitacion, name='aceptar_invitacion'),
    path('expulsar-miembro/<int:id_joven>/<int:id_equipo>', view=EliminarDelEquipo, name='expulsar_miembro'),
    path('rechazar-postulacion/<int:id_joven>/<int:id_equipo>', view=RechazarPostulacion, name='rechazar_postulacion'),
    path('salir-del-equipo/<int:id_joven>/<int:id_equipo>', view=SalirDelEquipo, name='salir_del_equipo'),
    path('rechazar-invitacion/<int:id_joven>/<int:id_equipo>', view=RechazarInvitacion, name='rechazar_invitacion'),
    path('retirar-postulacion/<int:id_joven>/<int:id_equipo>', view=RetirarPostulacion, name='retirar_postulacion'),
    path('cambiar-lider/<int:id_joven>/<int:id_equipo>', view=CambiarLider, name='cambio_de_lider'),

    path('tablero-competencias-cognitivas/<int:id_equipo>', view=TableroEquipoCompetenciasCognitivas.as_view(), name='competencias_cognitivas'),
    path('tablero-competencias-habilidades-sociales/<int:id_equipo>', view=TableroEquipoCompetenciasHabilidadesSociales.as_view(), name='habilidades_sociales'),
    path('tablero-competencias-aptitudes-e-intereses/<int:id_equipo>', view=TableroEquipoCompetenciasAptitudesEIntereses.as_view(), name='aptitudes_e_intereses'),
    path('tablero-competencias-experiencias/<int:id_equipo>', view=TableroEquipoCompetenciasExperiencias.as_view(), name='competencias_experiencias'),

    path('rechazar-invitacion-organizacion/<int:id_organizacion>/<int:id_equipo>', view=RechazarInvitacionOrganizacion, name='rechazar_invitacion_de_organizacion'),
    path('aceptar-invitacion-organizacion/<int:id_organizacion>/<int:id_equipo>', view=AceptarInvitacionOrganizacion, name='aceptar_invitacion_de_organizacion'),
    path('rechazar-invitacion-reto/<int:id_reto>/<int:id_equipo>', view=RechazarInvitacionReto, name='rechazar_invitacion_de_reto'),
    path('aceptar-invitacion-reto/<int:id_reto>/<int:id_equipo>', view=AceptarInvitacionReto, name='aceptar_invitacion_de_reto'),
]

kairos/error/urls.py
from . import views
from django.urls import path

app_name = "error"

kairos/guia/urls.py
# Modulos Django
from django.urls import path

# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from . import views

app_name = "guia"

urlpatterns = [
    path('listado', views.ListadoRecursos.as_view(), name='listado'),
    path('registrar', views.RecursoRegistrar.as_view(), name='registrar'),
    path('modificar/<int:id_recurso>', views.ModificarRecurso.as_view(), name='modificar'),

    path('tipos/gestionar/',  views.ListadoTipoRecursos.as_view(), name='listado_tipo'),
    path('tipos/registrar',  views.TipoRecursoRegistrar.as_view(), name='registrar_tipo'),
    path('tipos/modificar/<int:id_tipo_recurso>',  views.ModificarTipoRecurso.as_view(), name='modificar_tipo'),

    path('guia-eslabon', views.ConsultarJovenesGuia.as_view(), name='consultar_guia_jovenes'),
    path("api/cargar-calificaciones", views.ApiCargarCalificaciones.as_view(), name="api_cargar_calificaciones"),
    path("api/calificar", views.ApiCalificar.as_view(), name="api_calificar"),
    path("api/realidad", views.APIRecursosRealidad.as_view(), name="api_realidad"),
]

kairos/pqrs/urls.py
# Modulos Django
from django.urls import path
# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from .views import *

app_name = "pqrs"

urlpatterns = [
    path('enviar/', CrearSolicitudPQRS.as_view(), name='enviar_pqrs'),
]

kairos/retos/urls.py
# Modulos Django
from django.urls import path

# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from .views import *

app_name = "retos"

urlpatterns = [
    path('gestionar/', view=RetosListado.as_view(), name='listado'),
    path('consultar/', view=RetosConsultar.as_view(), name='consultar'),
    path('registrar/', view=RetosRegistrar.as_view(), name='registrar'),
    path('registrar/<int:id_solicitud>', view=RetosRegistrarDesdeSolicitud.as_view(), name='registrar_desde_solicitud'),
    path('modificar/<int:id_reto>', view=RetosModificar.as_view(), name='modificar'),

    path('responder-cuartos/<int:id_reto>', view=retos_responder_cuartos, name='retos_responder_cuartos'),
    path('responder-cuartos/<int:id_reto>/<int:id_equipo>', view=retos_responder_cuartos, name='retos_responder_cuartos'),

    path('cuarto-descanso/<int:id_reto>', view=cuarto_descanso, name='cuarto_descanso'),
    path('cuarto-descanso/<int:id_reto>/<int:id_equipo>', view=cuarto_descanso, name='cuarto_descanso'),

    path('cuarto-finalizacion/<int:id_reto>', view=retos_cuarto_final, name='cuarto_finalizacion'),
    path('cuarto-finalizacion/<int:id_reto>/<int:id_equipo>', view=retos_cuarto_final, name='cuarto_finalizacion'),
    
    path('inicio-reto/<int:id_reto>', view=inicio_reto, name='inicio_reto'),
    path('inicio-reto/<int:id_reto>/<int:id_equipo>', view=inicio_reto, name='inicio_reto'),
   
    path('abandonar-reto-joven/<int:id_reto>', view=abandonar_reto_joven, name='abandonar_reto'),
    path('abandonar-reto-joven/<int:id_reto>/<int:id_equipo>', view=abandonar_reto_joven, name='abandonar_reto'),
    
    path('cuestionario-reto/<int:id_reto>', view=retos_responder_cuartos, name='cuestionario_reto'),

    path('consultar-retos/', view=ConsultarListaRetos.as_view(), name='consultar_retos'),
    path('consulta-reto/<int:pk>', view=ConsultarReto.as_view(), name='consultar_reto'),

    path("api/cargar-calificaciones", view=RetoApiCargarCalificaciones.as_view(), name="retos_api_cargar_calificaciones"),
    path("api/cargar-calificacion", view=RetoApiCargarCalificacion.as_view(), name="retos_api_cargar_calificacion"),
    path("api/calificar", view=RetoApiCalificarContenido.as_view(), name="retos_api_calificar"),
    path("api/guardar-cuarto-acto", view=RetoApiGuardarCuartoActo.as_view(), name="retos_api_guradar_cuarto_acto"),
    path("api/guardar-pregunta", view=RetoApiGuardarCuartoPregunta.as_view(), name="retos_api_guardar_pregunta"),
    path("api/guardar-tiempo-pregunta", view=RetoApiGuardarTiempoPregunta.as_view(), name="retos_api_guardar_tiempo_pregunta"),
    path("api/recalificar-cuarto-acto", view=RetoApiRecalificarCuartoActo.as_view(), name="retos_api_recalificar_cuarto_acto"),
    path("api/actualizar-ranking", view=RetoApiActualizarRanking.as_view(), name="retos_api_actualizar_ranking"),
    path("api/enviar-respuesta-pregunta", view=RetoApiEnviarRespuestaPregunta.as_view(), name="retos_api_enviar_respuesta_pregunta"),
    path("api/calificar_competencias_joven", view=RetoApiCalificarCompetenciasJoven.as_view(), name="api_calificar_competencias"),
    
    path('retos/modificar_solicitud/<int:id_solicitud_reto>', view=ModificarSolicitudesRetos.as_view(), name='organizacion_modificar_solicitudes_retos'),
    path('solicitudes-organizaciones/', view=GestionDeSolicitudesRetosOrganizaciones.as_view(), name='solicitudes_retos_organizaciones'),
    path('solicitudes-jovenes/', view=GestionDeSolicitudesRetosJovenes.as_view(), name='solicitudes_solicitudes_jovenes'),
    path('solicitudes-jovenes-equipos/', view=GestionDeSolicitudesRetosJovenesEquipos.as_view(), name='solicitudes_solicitudes_jovenes_equipos'),

    path('enviar-solicitud-joven/<int:id_joven>/<int:id_reto>', view=RetoJovenEnviarSolicitud, name='retos_enviar_solicitud_joven'),
    path('rechazar-solicitud-joven/<int:id_joven>/<int:id_reto>', view=RetoJovenRechazarSolicitud, name='retos_rechazar_solicitud_joven'),
    path('aceptar-solicitud-joven/<int:id_joven>/<int:id_reto>', view=RetoJovenAceptarSolicitud, name='retos_aceptar_solicitud_joven'),
    path('finalizar-solicitud-joven/<int:id_joven>/<int:id_reto>', view=RetoJovenFinalizarRelacion, name='retos_finalizar_solicitud_joven'),

    path('enviar-solicitud-equipo/<int:id_joven>/<int:id_reto>', view=PostulacionLiderReto, name='retos_enviar_solicitud_equipo'),
    path('rechazar-solicitud-equipo/<int:id_equipo>/<int:id_reto>', view=RetoEquipoRetirarPostulacion, name='retos_rechazar_solicitud_equipo'),
    path('aceptar-solicitud-equipo/<int:id_equipo>/<int:id_reto>', view=RetoEquipoAceptarSolicitud, name='retos_aceptar_solicitud_equipo'),
    path('retirar-equipo-reto/<int:id_equipo>/<int:id_reto>', view=RetoLiderRetirarEquipo, name='retos_retirar_equipo'),

    path('invitar-equipos-jovenes/<int:id_reto>', view=InvitarEquiposJovenesAdministrador, name='retos_invitar_equipos_jovenes'),
    path('expulsar-miembros/<int:id_reto>', view=ExpulsarEquiposJovenesAdministrador, name='retos_expulsar_miembros'),

    path('pagina-espera', view=RetosPaginaEspera.as_view(), name='pagina_espera'),

    path('seleccion-jurados/<int:id_reto>', view=seleccion_jurados, name='seleccion_jurados'),    
    path('consultar-jurados-reto/<int:id_reto>', view=ConsultarJuradosReto.as_view(), name='consultar_jurados_reto'),
    path('eliminar-jurados-reto/<int:id_reto>/<int:id_jurado>', view=eliminar_jurado_del_reto, name='eliminar_jurado_reto'),
    path('asignar-jurados-equipo/<int:id_reto>/<int:id_jurado>', view=asignar_jurados_equipos, name='asignar_jurados_equipos'),
    path('eliminar-jurados-participante/<int:id_reto>/<int:id_jurado>/<int:id_paricipante>', view=eliminar_jurado_del_participante, name='eliminar_jurado_participante'),

    
    path('asignar-jurados-jovenes/<int:id_reto>/<int:id_jurado>', view=asignar_jurados_jovenes, name='asignar_jurados_jovenes'),

    path('seleccion-equipo/<int:id_reto>', view=seleccion_equipo, name='seleccion_equipo'),
    path('estamos-los-que-somos/<int:id_reto>/<int:id_equipo>', view=cuarto_espera_equipos, name='cuarto_espera_equipos'),
    path('reconocimiento-equipos/<int:id_reto>/<int:id_equipo>', view=cuarto_reconocimiento_equipos, name='cuarto_reconocimiento_equipos'),
    path("api/asistencia-equipos", view=ApiCambioDeAsistencia.as_view(), name="api_asistencia"),
    path("api/verificar-asistencia-equipos", view=ApiVerificarAsistencia.as_view(), name="api_verificar_asistencia"),
    path("api/cargar-pagina-finaizacion-miembros", view=RetoApiCargarPaginaFinalizacionMiembros.as_view(), name="api_cargar_pagina_finaizacion_miembros"),
    path("api/actualizar-boton-inicio-reto", view=RetoApiActualizarBotonRetoInicio.as_view(), name="api_actualizar_boton_inicio_reto"),
    path("api/notificar-correos", view=ApiNotificarCorreos.as_view(), name="api_notificar_correos"),
    path("api/confirmar-reto-finalizado", view=RetoApiConfirmarRetoFinalizado.as_view(), name="api_confirmar_reto_finalizado"),
    

    path('registrar-competencia', view=CompetenciasRegistrar.as_view(), name='registrar_competencia'),
    path('modificar-competencia/<int:id_competencia>', view=CompetenciasModificar.as_view(), name='modificar_competencia'),   
    path('listado-competencias', view=CompetenciasListado.as_view(), name='listado_competencias'),

    path('resultados-participantes/<int:id_reto>', view=ConsultarResultadosParticipantes.as_view(), name='resultados_participantes'),

    path('resultados-participante/<int:id_reto>', view=ConsultarResultadosParticipante.as_view(), name='resultados_participante'),

    # path('tipos/gestionar/', TipoRetoListado.as_view(), name='listado_tipos'),
    # path('tipos/consultar/', TipoRetoConsultar.as_view(), name='consultar_tipos'),
    # path('tipos/registrar', TipoRetoRegistrar.as_view(), name='registrar_tipo'),
    # path('tipos/modificar/<int:id_tipo>', TipoRetoModificar.as_view(), name='modificar_tipo'),
]

kairos/auditorias/models.py
from django.db import models

kairos/intereses/models.py
# Modulos Django
from django.db import models

# Modulos de plugin externos
from simple_history.models import HistoricalRecords

# Modulos de otras apps
# Modulos internos de la app

class Intereses(models.Model):
    nombre = models.CharField(max_length=50, verbose_name='nombre del interés*')
    descripcion = models.TextField(verbose_name='descripción*')
    activo = models.BooleanField(verbose_name="¿El interés se encuentra activo?", default=True)
    history = HistoricalRecords()

kairos/jurados/models.py
from django.db import models
from kairos.usuarios.models import Usuario


# Create your models here.
class Jurado(Usuario):

    def agregar_reto(self, reto):
        self.retos_jurados.add(reto)

    @staticmethod
    def buscar(id_jurado):
        try:
            jurado = Jurado.objects.get(id=id_jurado)
            return jurado
        except Jurado.DoesNotExist:
            return None


class RetroalimentacionJuradoEquipo(models.Model):
    detalle = models.ForeignKey('retos.DetalleEquipoReto', related_name='retroalimentacion_detalle_equipo', on_delete=models.PROTECT, null=True)
    retroalimentacion = models.CharField(max_length=100)
    
class RetroalimentacionJuradoJoven(models.Model):
    detalle = models.ForeignKey('retos.DetalleJovenReto', related_name='retroalimentacion_detalle_joven', on_delete=models.PROTECT, null=True)
    retroalimentacion = models.CharField(max_length=100)

kairos/ranking/models.py
from django.db import models

# Create your models here.

kairos/tableros/tablero_auditorias/models.py
from django.db import models

# Create your models here.

kairos/templates/equipos/solicitudes/solicitudes_equipo.html
{% extends 'base_tablas.html' %}
{% load static %}
{% load bootstrap4 %}
{% load extra_tags %}

{% block titulo %}
    Gestión de Solicitudes de Equipos 
{% endblock titulo %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="{% url "inicio" %}">Inicio</a></li>
    <li class="breadcrumb-item"><a href="">Equipos</a></li>
    <li class="breadcrumb-item active"><a href="">Gestión de Solicitudes</a></li>
    <li class="breadcrumb-item active"><a href="">{{filtro_actual}}</a></li>
{% endblock miga_pan %}

{% block titulo_pagina %}
    <i class="icon-people icon-orange"></i> Gestión de Solicitudes 
{% endblock titulo_pagina %}

{% block css %}
    <style>
        .buttons-html5{
            margin-right: 5px !important; 
            width: 70px;
        }

        .buttons-print{            
            width: 70px;
        }
    </style>
{% endblock css%}

{% block contenido %}
    {% block contenido_panel %}
        <div class="row">
            <div class="col-12">
                <form method="GET" class='col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'>  
                    <div class="my-1 btn btn-sm form-group my-1 mx-0 p-0" > 
                        <select class="btn btn-sm btn-outline-orange" style="width: 100px; margin: 0;" name="q" id="filtro" onchange="this.form.submit()">
                            <option value='Retos' style="height: 50px;">Retos</option>
                            <option value='Organizaciones' style="height: 50px;">Organizaciones</option>
                        </select>
                    </div>
                    {% for tipo in tipos %}
                        <input type="submit" name="tag" value="{{ tipo.nombre }}" class="btn btn-sm {% if tipo.nombre == tag %}btn-orange{% else %}btn-outline-orange{% endif %}">
                    {% endfor %}
                </form>
            </div>
            
            <div class="col-12 contenido">
                <div class="row">
                <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="tab-content p-15 rounded bg-white">
                        <div class="tab-pane fade active show">
                            <div class="row m-b-9">
                                <div class="col-md-12">
                                    <p class="mb-1">
                                        <i>A continuación se presentan las Solicitudes de los {{filtro_actual}} que quieren pertenecer un equipo:</i>
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 m-t-5">
                                    <div class="table-fix">
                                        <table class="table table-bordered table-striped table-td-valign-middle datatable">
                                            <thead>
                                                <tr>
                                                    {% for cabecera in nombre_columnas %}
                                                        <th>{{cabecera}}</th>
                                                    {% endfor %}
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {{filtro_actual}}
                                            {% for solicitud in solicitudes %}
                                                <tr>
                                                    {% if filtro_actual == 'Organizaciones' %}
                                                        <td>{{solicitud.equipo}}</td>
                                                        <td>
                                                            <a href="{% url 'organizaciones:joven_detalle' solicitud.organizacion.id %}"><small><b>{{solicitud.organizacion}}</b></small></a> 
                                                        </td>
                                                    {% else %}
                                                        <td>{{solicitud.equipo}}</td>
                                                        <td>
                                                            <a href="{% url 'retos:consultar_reto' solicitud.reto.id %}"><small><b>{{solicitud.reto}}</b></small></a> 
                                                        </td>
                                                    {% endif %}

                                                    {% if solicitud.estado == 'Postulado' %}
                                                        <th><span class="label label-aqua">{{solicitud.estado}}</span></th>
                                                    {% else %}
                                                        <th><span class="label label-lime">{{solicitud.estado}}</span></th>
                                                    {% endif %}
                                                    
                                                    <td align="center">
                                                        <div class="row">
                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                                {% if solicitud.estado == 'Invitado' %}
                                                                    {% if filtro_actual == 'Organizaciones' %}
                                                                        <a class="btn btn-sm btn-green" href="{% url "equipos:aceptar_invitacion_de_organizacion" solicitud.organizacion.id solicitud.equipo.id %}"><small><b>Aceptar Invitación</b></small></a>
                                                                        <a class="btn btn-sm btn-blue" href="{% url "equipos:rechazar_invitacion_de_organizacion" solicitud.organizacion.id solicitud.equipo.id %}"><small><b>Cancelar Invitación</b></small></a>
                                                                    {% else %}
                                                                        <a class="btn btn-sm btn-green" href="{% url "retos:retos_aceptar_solicitud_equipo" solicitud.equipo.id solicitud.reto.id %}"><small><b>Aceptar Invitación</b></small></a>
                                                                        <a class="btn btn-sm btn-blue" href="{% url "retos:retos_rechazar_solicitud_equipo" solicitud.equipo.id solicitud.reto.id %}"><small><b>Cancelar Invitación</b></small></a>
                                                                    {% endif %}
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock contenido_panel %}
{% endblock contenido %}

{% block js %}
{{ block.super }}
    <script>
        $("#filtro").val('{{filtro_actual}}');
    </script>
{% endblock js %}