config/urls.py
from django.contrib import admin
from django.urls import path, include
from kairos.usuarios.views import inicio
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", inicio, name='inicio'),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    #path('auth/', include('magiclink.urls', namespace='magiclink')),
    path('app/usuarios/', include('kairos.usuarios.urls', namespace='usuarios')),
    path('app/organizaciones/', include('kairos.organizaciones.urls', namespace='organizaciones')),
    path('app/perfiles-deseados/', include('kairos.perfiles_deseados.urls', namespace='perfiles_deseados')),
    path('app/intereses/', include('kairos.intereses.urls', namespace='intereses')),
    path('app/retos/', include('kairos.retos.urls', namespace='retos')),
    path('app/contenido/', include('kairos.contenido.urls', namespace='contenido')),
    path('app/insignias/', include('kairos.insignias.urls', namespace='insignias')),
    path('app/cuestionarios/', include('kairos.formularios.urls', namespace='formularios')),
    path('app/calificaciones/', include('kairos.calificaciones.urls', namespace='calificaciones')),
    path('app/tandas/', include('kairos.tandas_formularios.urls', namespace='tandas')),
    path('app/tablero-organizaciones/', include('kairos.tableros.tablero_organizaciones.urls', namespace='tablero_organizaciones')),
    path('app/tablero-jovenes/', include('kairos.tableros.tablero_jovenes.urls', namespace='tablero_jovenes')),
    path('app/tablero-auditorias/', include('kairos.tableros.tablero_auditorias.urls', namespace='tablero_auditorias')),
    path('app/equipos/', include('kairos.equipos.urls', namespace='equipos')),
    path('app/auditorias/', include('kairos.auditorias.urls', namespace='auditorias')),
    path('app/guia/', include('kairos.guia.urls', namespace='guia')),
    path('app/ranking/', include('kairos.ranking.urls', namespace='ranking')),
    path('app/pqrs/', include('kairos.pqrs.urls', namespace='pqrs')),
    path('app/cuartos/', include('kairos.cuartos.urls', namespace='cuartos')),
    path('app/jurados/', include('kairos.jurados.urls', namespace='jurados')),
    path('app/habilidades-del-futuro/', include('kairos.habilidades_del_futuro.urls', namespace='habilidades_del_futuro')),

    path('select2/', include('django_select2.urls')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Handler errors
handler404 = 'kairos.error.views.error_404'
handler500 = 'kairos.error.views.error_500'

kairos/cuartos/urls.py
# Modulos Django
from django.urls import path

# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from .views import *

app_name = "cuartos"


urlpatterns = [
    path('listado/<int:id_reto>', CuartoListado.as_view(), name='listado'),
    path('registrar/<int:id_reto>', CuartoRegistrar.as_view(), name='registrar'),
    path('modificar/<int:id_reto>/<int:id_cuarto>', CuartoModificar.as_view(), name='modificar'),

    path('listado-tipos', TipoCuartoListado.as_view(), name='tipo_listado'),
    path('registrar-tipo', TipoCuartoRegistrar.as_view(), name='tipo_registrar'),
    path('modificar-tipo/<int:id_tipo>', TipoCuartoModificar.as_view(), name='tipo_modificar'),
    
    path('listado-actos/<int:id_reto>/<int:id_cuarto>', ActosListado.as_view(), name='acto_listado'),
    path('registrar-acto/<int:id_reto>/<int:id_cuarto>', ActoRegistrar.as_view(), name='acto_registrar'),
    path('modificar-acto/<int:id_reto>/<int:id_acto>/<int:id_cuarto>', ActoModificar.as_view(), name='acto_modificar'),

    path('listado-preguntas/<int:id_reto>/<int:id_cuarto>', PreguntasListado.as_view(), name='preguntas_listado'),
    path('registrar-preguntas/<int:id_reto>/<int:id_cuarto>', PreguntaRegistrar.as_view(), name='pregunta_registrar'),
    path('modificar-preguntas/<int:id_reto>/<int:id_cuarto>/<int:id_pregunta>', PreguntaModificar.as_view(), name='preguntas_modificar'),

    path('listado-opciones/<int:id_reto>/<int:id_cuarto>/<int:id_pregunta>', OpcionListado.as_view(), name='opciones_listado'),
    path('registrar-opciones/<int:id_reto>/<int:id_cuarto>/<int:id_pregunta>', OpcionRegistrar.as_view(), name='opcion_registrar'),
    path('modificar-opciones/<int:id_reto>/<int:id_cuarto>/<int:id_pregunta>/<int:id_opcion>', OpcionModificar.as_view(), name='opcion_modificar'),

]

kairos/error/urls.py
from . import views
from django.urls import path

app_name = "error"

kairos/guia/urls.py
# Modulos Django
from django.urls import path

# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from . import views

app_name = "guia"

urlpatterns = [
    path('listado', views.ListadoRecursos.as_view(), name='listado'),
    path('registrar', views.RecursoRegistrar.as_view(), name='registrar'),
    path('modificar/<int:id_recurso>', views.ModificarRecurso.as_view(), name='modificar'),

    path('tipos/gestionar/',  views.ListadoTipoRecursos.as_view(), name='listado_tipo'),
    path('tipos/registrar',  views.TipoRecursoRegistrar.as_view(), name='registrar_tipo'),
    path('tipos/modificar/<int:id_tipo_recurso>',  views.ModificarTipoRecurso.as_view(), name='modificar_tipo'),

    path('guia-eslabon', views.ConsultarJovenesGuia.as_view(), name='consultar_guia_jovenes'),
    path("api/cargar-calificaciones", views.ApiCargarCalificaciones.as_view(), name="api_cargar_calificaciones"),
    path("api/calificar", views.ApiCalificar.as_view(), name="api_calificar"),
    path("api/realidad", views.APIRecursosRealidad.as_view(), name="api_realidad"),
]

kairos/pqrs/urls.py
# Modulos Django
from django.urls import path
# Modulos de plugin externos

# Modulos de otras apps

# Modulos internos de la app
from .views import *

app_name = "pqrs"

urlpatterns = [
    path('enviar/', CrearSolicitudPQRS.as_view(), name='enviar_pqrs'),
]

kairos/auditorias/models.py
from django.db import models

kairos/calificaciones/models.py
# Modulos Django
from django.contrib.postgres.fields import JSONField
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Modulos de plugin externos
from simple_history.models import HistoricalRecords

# Modulos de otras apps
from kairos.usuarios.models import Usuario

# Modulos internos de la app

class CalificacionFormulario(models.Model):
    formulario = models.ForeignKey('formularios.Formularios', on_delete=models.CASCADE, verbose_name='formulario a calificar',
                                   related_name='formulario_calificado')
    usuario = models.ForeignKey('usuarios.Usuario', on_delete=models.CASCADE, verbose_name='usuario que califica',
                                related_name='usuario_calificador_formulario')
    calificacion = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(5), MinValueValidator(0)],
                                               verbose_name='calificación de 1 a 5')
    history = HistoricalRecords()


class CalificacionRespuestasJoven(models.Model):
    respuestas = models.ForeignKey('respuestas_formularios.RespuestasJoven', on_delete=models.CASCADE, verbose_name="respuestas_calificadas", related_name='calificacion_respuesta')
    resultadoD48 = JSONField(null=True)  # {'respondidas':...,'correctas':..., 'porcentaje': ...., 'resultado': ...}
    puntajesSterret = JSONField(null=True)  # {'global': ..., 'competencias': {competencia1: {puntaje: ..., resultado: ...}, competencia2: {puntaje: ..., resultado: ...}}}
    promediosLiderazgo = JSONField(null=True)  # {'dimensiones': {'transaccional': ..., 'transformacional': ...,, 'laizzes_faire': ....} 'competencias': {competencia1: {promedio: ..., resultado: ...}, competencia2: {promedio: ..., resultado: ...}}}
    resultadoSM = JSONField(null=True)  # {'respondidas':...,'correctas':..., 'porcentaje': ...., 'resultado': ...}
    puntajesCHASIDE = JSONField(null=True)  # {'orden': [('C',0),('S',1),...] 'competencias': {competencia1: {promedio: ..., resultado: ...}, competencia2: {promedio: ..., resultado: ...}}}
    history = HistoricalRecords()

kairos/experiencias_jovenes/models.py
from django.db import models
from simple_history.models import HistoricalRecords

TIEMPO = (
    ("1", "Menos de 1 año"),
    ("2", "Entre 1 y 2 años"),
    ("3", "Entre 2 y 4 años"),
    ("4", "Más de 5 años")
)

SI_NO = (
    (True, "Sí"),
    (False, "No")
)

class ClubesJuveniles(models.Model):
    joven = models.ForeignKey('usuarios.Joven', related_name="clubes_del_joven", on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, verbose_name='Nombre del club/grupo')
    tribu = models.ForeignKey('insignias.Tribus', verbose_name='¿En cuál tribu ubicarías el club juvenil al que perteneces o pertenecías?',
                              on_delete=models.CASCADE)
    tiempo = models.CharField(max_length=10, choices=TIEMPO,
                              verbose_name='¿Cuánto tiempo perteneciste o has pertenecido al club/grupo juvenil?')
    pertenece_actualmente = models.BooleanField(verbose_name='¿Sigues perteneciendo?', null=False, blank=True, choices=SI_NO, default=False)
    history = HistoricalRecords()


class Voluntariados(models.Model):
    joven = models.ForeignKey('usuarios.Joven', related_name="voluntariados_del_joven", on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100,
                              verbose_name='Rol o cargo como voluntario')
    tribu = models.ForeignKey('insignias.Tribus', verbose_name='¿En cuál tribu ubicarías tu voluntariado?', on_delete=models.CASCADE)
    tiempo = models.CharField(max_length=10, choices=TIEMPO,
                              verbose_name='¿Cuánto tiempo fuiste o has sido voluntario?')
    pertenece_actualmente = models.BooleanField(verbose_name='¿Sigues perteneciendo?', null=False, blank=True, choices=SI_NO, default=False)
    history = HistoricalRecords()


class Laborales(models.Model):
    joven = models.ForeignKey('usuarios.Joven', related_name="experiencias_laborales_del_joven", on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, verbose_name='Cargo por el que te contrataron')
    tribu = models.ForeignKey('insignias.Tribus', verbose_name='¿En cuál tribu ubicarías el trabajo por el fuiste contratado?',
                              on_delete=models.CASCADE)
    tiempo = models.CharField(max_length=10, choices=TIEMPO, verbose_name='¿Cuánto tiempo estuviste o has estado contratado?')
    pertenece_actualmente = models.BooleanField(verbose_name='¿Sigues perteneciendo?', null=False, blank=True, choices=SI_NO, default=False)
    history = HistoricalRecords()


class Independientes(models.Model):
    joven = models.ForeignKey('usuarios.Joven', related_name="trabajos_independientes_del_joven", on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, verbose_name='Servicio/producto que producías/produces y vendías/vendes tú mismo')
    tribu = models.ForeignKey('insignias.Tribus', verbose_name='¿En cuál tribu ubicarías tu trabajo como independiente?', on_delete=models.CASCADE)
    tiempo = models.CharField(max_length=10, choices=TIEMPO, verbose_name='¿Cuánto tiempo trabajas o has trabajado como '
                                                                          'independiente?')
    pertenece_actualmente = models.BooleanField(verbose_name='¿Sigues perteneciendo?', null=False, blank=True, choices=SI_NO, default=False)
    history = HistoricalRecords()


class Emprendimientos(models.Model):
    joven = models.ForeignKey('usuarios.Joven', related_name="emprendimientos_del_joven", on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, verbose_name='¿En qué consistía tu negocio?')
    tribu = models.ForeignKey('insignias.Tribus', verbose_name='¿En cuál tribu ubicarías tu emprendimiento?', on_delete=models.CASCADE)
    tiempo = models.CharField(max_length=10, choices=TIEMPO, verbose_name='¿En qué consistía o consiste tu negocio?')
    pertenece_actualmente = models.BooleanField(verbose_name='¿Sigues perteneciendo?', null=False, blank=True, choices=SI_NO, default=False)
    history = HistoricalRecords()

kairos/habilidades_del_futuro/models.py
# Modulos Django
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Modulos de plugin externos
from simple_history.models import HistoricalRecords
import os

# Modulos de otras apps

# Modulos internos de la app


def subir_img_insignia(instance, filename):
    return "habilidades_futuro/%s" % (filename.encode('ascii', 'ignore'))


class Habilidad(models.Model):
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    nombre = models.CharField(max_length=50, verbose_name="nombre de la habilidad*")
    descripcion = models.TextField(verbose_name="descripción de la habilidad*")
    imagen = models.FileField(upload_to=subir_img_insignia, verbose_name="imagen de la habilidad*")
    link_video = models.CharField(max_length=100, verbose_name="enlace a video explicativo (url)*", blank=True)
    descripcion_video = models.TextField(verbose_name="descripción del video*", blank=True)
    como_se_mide = models.TextField(verbose_name="Como se mide*", blank=True)
    competencias_asociadas = models.ManyToManyField('formularios.Competencias', related_name="habilidades_del_futuro_competencias",
                                                    verbose_name="competencias asociadas", blank=True
                                                    )
    activo = models.BooleanField(verbose_name="¿La habilidad se encuentra activa?", default=True)
    orden = models.IntegerField(verbose_name="Orden con respecto a las otras habilidades", blank=True,
                                default=0)
    history = HistoricalRecords()

    def __str__(self):
        return self.nombre

    def crear_habilidad_visitada_joven(self, id_usuario: int):
        '''
            Función que crea la competencia visitada para el joven
        '''
        HabilidadVisitada.objects.get_or_create(
            usuario_id=id_usuario,
            habilidad_id=self.pk
        )

    def calificar_habilidad_joven(self, id_usuario: str):
        '''
            Función que califica la competencia como visitada
        '''
        habilidad_visitada = HabilidadVisitada.objects.get(
            usuario_id=id_usuario,
            habilidad_id=self.pk
        )
        if habilidad_visitada.visitado == 0:
            habilidad_visitada.visitado = 1
            habilidad_visitada.save()

    @staticmethod
    def obtener_activos() -> 'Queryset<Habilidad>':
        '''
            Función que retorna todas las habilidades del futuro activas
            Queryset<Habilidad>: Queryset<Habilidad>
        '''
        habilidades = Habilidad.objects.filter(activo=True)
        return habilidades
    @staticmethod
    def buscar(id_habilidad:str) -> 'Habilidad':
        '''
            Funciión que busca la habilidad por id_habilidad
            y retorna la habilidad en caso de encontrarla.
        '''
        habilidad = Habilidad.objects.get(pk=id_habilidad)
        return habilidad

    class Meta:
        ordering = ['orden']


class HabilidadVisitada(models.Model):
    habilidad = models.ForeignKey('Habilidad', on_delete=models.CASCADE, verbose_name='habilidad calificado',
                                  related_name='habilidad_visitada_del_usuario')
    usuario = models.ForeignKey('usuarios.Usuario', on_delete=models.CASCADE, verbose_name='usuario que califica',
                                related_name='usuario_visitador_habilidad')
    visitado = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(1), MinValueValidator(0)],
                                           verbose_name='calificación: 1 visitado, 0 no visitado')
    history = HistoricalRecords()

    @staticmethod
    def obtener_todos(id_joven: str) -> 'Queryset<HabilidadVisitada>':
        '''
            Función que retorna todas las habilidades del joven
            Queryset<HabilidadVisitada>: Queryset<HabilidadVisitada>
        '''
        habilidades_visitadas = HabilidadVisitada.objects.filter(usuario_id=id_joven)
        return habilidades_visitadas

    @staticmethod
    def obtener_visitados(id_joven: str) -> 'Queryset<HabilidadVisitada>':
        '''
            Función que retorna todas las habilidades visitadas
            por el joven
            Queryset<HabilidadVisitada>: Queryset<HabilidadVisitada>
        '''
        habilidades_visitadas = HabilidadVisitada.obtener_todos(id_joven).filter(visitado=1)
        return habilidades_visitadas

kairos/intereses/models.py
# Modulos Django
from django.db import models

# Modulos de plugin externos
from simple_history.models import HistoricalRecords

# Modulos de otras apps
# Modulos internos de la app

class Intereses(models.Model):
    nombre = models.CharField(max_length=50, verbose_name='nombre del interés*')
    descripcion = models.TextField(verbose_name='descripción*')
    activo = models.BooleanField(verbose_name="¿El interés se encuentra activo?", default=True)
    history = HistoricalRecords()

kairos/ranking/models.py
from django.db import models

# Create your models here.

kairos/tableros/tablero_auditorias/models.py
from django.db import models

# Create your models here.

kairos/templates/cuartos/preguntas/listado.html
{% extends 'base_tablas.html' %}
{% load static %}

{% block titulo %}
    Gestión Preguntas
{% endblock titulo %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="{% url "inicio" %}">Inicio</a></li>
    <li class="breadcrumb-item"><a href="{% url "retos:listado" %}">Gestión Retos</a></li>
    <li class="breadcrumb-item"><a href="{% url "cuartos:listado" reto.id %}">Gestión Preguntas</a></li>
    <li class="breadcrumb-item active"> Gestión Preguntas</li>
{% endblock miga_pan %}

{% block titulo_pagina %}
    Gestión Preguntas
{% endblock titulo_pagina %}

{% block contenido_panel %}
    <div class="row m-b-9">
        <div class="col-md-12">
            <p class="mb-1">
                <i>A continuación se presentan las preguntas y sus diferentes herramientas para su gestión.</i>
            </p>
        </div>
        <div class="col-md-12" align="right">
            <a class="btn btn-primary" href="{% url "cuartos:pregunta_registrar" reto.id cuarto.id %}"><i class="fas fa-plus"></i> Registrar Pregunta</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12 m-t-5">
            <div class="table-fix">
                <table class="table table-bordered table-striped table-td-valign-middle datatable">
                    <thead>
                    <tr>
                        <th>Enunciado</th>
                        <th>Dificultad</th>                        
                        <th>Tiempo Limite</th>
                        <th>Orden</th>
                        <th>Activo</th>
                        <th>Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for pregunta in preguntas %}
                        <tr>
                            <td>{{pregunta.enunciado}}</td>
                            <td>{{pregunta.dificultad}}</td>
                            <td>{{pregunta.tiempo_limite}}</td>
                            <th>{{pregunta.cuarto_pregunta_pregunta.all.first.orden }}</th>
                            <td align="center">
                                {% if pregunta.activo == True %}
                                    <span class="label label-lime">ACTIVO</span>
                                {% else %}
                                    <span class="label label-secondary">INACTIVO</span>
                                {% endif %}
                            </td>
                            <td align="center">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <a title="Modificar" href="{% url "cuartos:preguntas_modificar" reto.id cuarto.id pregunta.id %}"><i class="fas fa-pen-alt"></i></a>
                                        <a title="Opciones" href="{% url "cuartos:opciones_listado" reto.id cuarto.id pregunta.id %}"><i class="fas fa-cog"></i></a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>                   
                </table>                
            </div>
            <div class="col-md-12 mt-3" align="left">
                <a class="btn btn-primary" href="{% url "cuartos:listado" reto.id %}"><i class="fas fa-arrow-left"></i> Atrás </a>
            </div>
        </div>
    </div>
{% endblock contenido_panel %}

kairos/templates/cuartos/preguntas/modificar.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block titulo %}
    Modificar Pregunta
{% endblock titulo %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="{% url "inicio" %}">Inicio</a></li>
    <li class="breadcrumb-item"><a href="{% url "retos:listado" %}">Gestión Retos</a></li>
    <li class="breadcrumb-item"><a href="{% url "cuartos:listado" reto.id %}">Gestión Cuartos</a></li>
    <li class="breadcrumb-item"><a href="{% url "cuartos:acto_listado" reto.id cuarto.id %}">Gestión Preguntas</a></li>
    <li class="breadcrumb-item active">Modificar Pregunta</li>
{% endblock miga_pan %}

{% block titulo_pagina %}
    Modificar Pregunta
{% endblock titulo_pagina %}

{% block contenido_panel %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
            <div class="col-12 mb-2">
                <p class="mb-1">
                    <i>El siguiente formulario permite modificar las diferentes características de una pregunta.</i>
                </p>
            </div>
            {% for campo in form %}
                {% if campo.name == 'activo'%}
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12" align="left">
                        {% bootstrap_field campo field_class="form-check checkbox checkbox-css pt-0 checkbox-inline" placeholder="" %}
                    </div>
                {% else %}
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                        {% bootstrap_field campo placeholder="" %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-6" align="left">
                <a class="btn btn-secondary" href="{% url "cuartos:preguntas_listado" reto.id cuarto.id %}"><i class="fa fa-angle-left"></i> Atrás</a>
            </div>
            <div class="col-6" align="right">
                <button class="btn btn-primary" type="submit">Modificar Acto <i class="fa fa-angle-right"></i></button>
            </div>
        </div>
    </form>
{% endblock contenido_panel %}

kairos/templates/cuartos/preguntas/registrar.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block titulo %}
    Registrar Pregunta
{% endblock titulo %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="{% url "inicio" %}">Inicio</a></li>
    <li class="breadcrumb-item"><a href="{% url "retos:listado" %}">Gestión Retos</a></li>
    <li class="breadcrumb-item"><a href="{% url "cuartos:listado" reto.id %}">Gestión Cuartos</a></li>
    <li class="breadcrumb-item"><a href="{% url "cuartos:acto_listado" reto.id cuarto.id %}">Gestión Preguntas</a></li>
    <li class="breadcrumb-item active">Registrar Pregunta</li>
{% endblock miga_pan %}

{% block titulo_pagina %}
    Registrar Pregunta
{% endblock titulo_pagina %}

{% block contenido_panel %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
            <div class="col-12 mb-2">
                <p class="mb-1">
                    <i>El siguiente formulario permite el registro de una pregunta en el sistema.</i>
                </p>
            </div>
            {% for campo in form %}
                {% if campo.name == 'activo'%}
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12" align="left">
                        {% bootstrap_field campo field_class="form-check checkbox checkbox-css pt-0 checkbox-inline" placeholder="" %}
                    </div>
                {% else %}
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                        {% bootstrap_field campo placeholder="" %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-6" align="left">
                <a class="btn btn-secondary" href="{% url "cuartos:preguntas_listado" reto.id cuarto.id %}"><i class="fa fa-angle-left"></i> Atrás</a>
            </div>
            <div class="col-6" align="right">
                <button class="btn btn-primary" type="submit">Registrar Pregunta <i class="fa fa-angle-right"></i></button>
            </div>
        </div>
    </form>
{% endblock contenido_panel %}